<a href="https://colab.research.google.com/github/megharajs07/DAV1/blob/main/DAV_01_Numpy_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [ ]:
import numpy as np
a = np.array([[23,4,43],
              [12,89,3],
              [69,420,0]])

b = np.sort(a)

In [ ]:
b

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [ ]:
A = np.arange(10).reshape(5,2)
B = np.arange(2).reshape(2,1)
c = np.dot(A,B)
c.shape

(5, 1)

In [ ]:
A = np.arange(12).reshape(3, 4)
B = np.array([1, 2, 3])
print(A+B)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
b = np.sort(a)

In [ ]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [ ]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [ ]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
import numpy as np
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

46

In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [ ]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [ ]:

arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])