<a href="https://colab.research.google.com/github/megharajs07/DAV1/blob/main/DAV_01_Numpy_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a= np.arange(4)
print(a)

[0 1 2 3]


In [ ]:
b = a.reshape(2,2) # Shallow copy
print(b)

[[0 1]
 [2 3]]


In [ ]:
a[0] = 100 # Modifying a[0]
print(a)

[100   1   2   3]


In [ ]:
print(b) # value of b[0][0] is also modified

[[100   1]
 [  2   3]]


In [ ]:
a = np.arange(4)
print(a)

b = a + 2 # deepcopy
print(b)

[0 1 2 3]
[2 3 4 5]


In [ ]:
a[0] = 100
print("a", a)
print("b", b) # No change in the values of b

a [100   1   2   3]
b [2 3 4 5]


### Slicing:

In [2]:
import numpy as np
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = a[::2]
print(b)

[0 2 4 6 8]


In [4]:
b[1]= 1000
print(b)

[   0 1000    4    6    8]


In [5]:
a

array([   0,    1, 1000,    3,    4,    5,    6,    7,    8,    9])

In [6]:
np.shares_memory(a,b) # If returns True - its a Shallow Copy

True

In [7]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b = a + 0
np.shares_memory(a,b) # If returns False - its a Deep Copy

False

### Mask

In [9]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
mask = a % 2 == 0
b = a[mask]
b

array([0, 2, 4, 6, 8])

In [12]:
np.shares_memory(a, b)

False

- shallow copy: reshape and slicing
- deep copy: arthematic operations and masking

In [14]:
# np.shares_memory doesn't work on lists as the memory in lists is not shared by default.
a = [1, 2, 3]
b = a
np.shares_memory(a, b)

False

In [15]:
a[0] = 20
print(b)

[20, 2, 3]


In [16]:
a = np.array([0,1,2,3,4,5])
b = a[a%1 == 0]
b[0] = 10
a[:2]

array([0, 1])

## Shallow copy can be created using .view() method.

In [17]:
a = np.arange(10)

In [18]:
s_copy = a.view()

In [19]:
s_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
s_copy[4] = 20
s_copy

array([ 0,  1,  2,  3, 20,  5,  6,  7,  8,  9])

In [22]:
a

array([ 0,  1,  2,  3, 20,  5,  6,  7,  8,  9])

In [23]:
np.shares_memory(a, s_copy)

True

## Deep copy can be created using .copy() method.

In [24]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
b = a.copy() # will create a deepcopy since it's homogeneous arr
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
np.shares_memory(a, b)

False

# Splitting an array
- np.split
    - integers
    - lists
- It takes an argument indices_or_sections.
- If indices_or_sections is an integer, n, the array will be divided into n equal arrays along axis.
- If such a split is not possible error is raised.
- If indices_or_sections is 1D array of sorted integers, the entries indicate where along axis the array is split.
- If an index exceeds the dimention of the array along axis, an empty subarray is returned correspondently.

In [27]:
x = np.arange(9)
print(x)
print(len(x))

[0 1 2 3 4 5 6 7 8]
9


In [28]:
splitted_list = np.split(x,3)
splitted_list

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [31]:
print(splitted_list[0])
print(splitted_list[1])
print(splitted_list[2])

[0 1 2]
[3 4 5]
[6 7 8]


In [32]:
print(x)

[0 1 2 3 4 5 6 7 8]


In [34]:
splitted_list = np.split(x,2) #In this case there are 9 elements in x and cant be split into 2 equal parts. Hence an "Error" is expected

ValueError: array split does not result in an equal division

In [35]:
x = np.arange(9)
splitted_list = np.split(x, [4]) #can be split with the index. It'll split until the index 4 as first array and the rest as second array
splitted_list

[array([0, 1, 2, 3]), array([4, 5, 6, 7, 8])]

In [38]:
x = np.arange(9)
splitted_list = np.split(x,[4,7]) # Multiple indecies can be passed to split accordingly
splitted_list

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

Above code has splitted the array into 3 parts:
- part 1: all the elements before index 4
- part 2: all the elements in range [4,7] (4 inclusive and 7 exclusive)
- part 3: all the elements after 7 - 7 inclusive

In [39]:
x = np.arange(16).reshape(4,-1)
x.shape

(4, 4)

In [40]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
x.ndim

2

- hsplit: divides array on horizantal axis
- vsplit: divides array on vertical axis

In [43]:
np.hsplit(x, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [48]:
np.hsplit(x, 3)

ValueError: array split does not result in an equal division

In [49]:
np.hsplit(x, [3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [45]:
np.hsplit(x, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [46]:
np.vsplit(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [47]:
np.vsplit(x,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [50]:
np.vsplit(x,3)

ValueError: array split does not result in an equal division

In [51]:
np.vsplit(x,[3])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

## Stacking:
- vstack
- hstack
- concatenate: can be used with both vstack and hstack by specifying axis

In [52]:
a = np.array([1,5])
b = np.array([2,6])
c = np.array([3,7])
print(a)
print(b)
print(c)

[1 5]
[2 6]
[3 7]


In [54]:
''' To print in the below format
[[1, 5],
 [2, 6],
 [3, 7]
]
We can use vstack. vstack will vertically join the arrays'''

np.vstack([a,b,c]) # if len(row) == number of columns; vstack will return an stacked array

array([[1, 5],
       [2, 6],
       [3, 7]])

In [55]:
a = np.array([1,5,1]) # if len(row) != number of columns we receive an error for vstack
b = np.array([2,6])
c = np.array([3,7])
np.vstack([a,b,c])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [56]:
a = np.arange(10, 15).reshape(5, 1)
a

array([[10],
       [11],
       [12],
       [13],
       [14]])

In [58]:
a.shape

(5, 1)

In [60]:
b = np.arange(15).reshape(5,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [61]:
b.shape

(5, 3)

In [62]:
np.hstack([a,b])

array([[10,  0,  1,  2],
       [11,  3,  4,  5],
       [12,  6,  7,  8],
       [13,  9, 10, 11],
       [14, 12, 13, 14]])

concatenate: expects you to pass all arrays of same dimension

In [68]:
a = np.array([[10, 11, 12]]) # 2 dimentional
b = np.array([[1, 2, 3], [4, 5, 6]]) # 2 dimentional
np.concatenate((a,b))

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [69]:
a = np.array([10, 11, 12]) # 1 dimentional
b = np.array([[1, 2, 3], [4, 5, 6]]) # 2 dimentional
np.concatenate((a,b))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [72]:
a = np.array([[10,11,12]]) # 2 dim
b = np.array([[1,2,3], [4,5,6]]) # 2 dim
np.vstack((a, b))

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [73]:
a = np.array([10,11,12]) # 1 dim
b = np.array([[1,2,3], [4,5,6]]) # 2 dim
np.vstack((a, b))

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [74]:
a = np.array([[10,11,12]]) # 2 dim
b = np.array([[1,2,3], [4,5,6]]) # 2 dim
np.concatenate((a, b))

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [75]:
b = np.array([[1, 2, 3], [4, 5, 6]]) # 2 dim
print(b)

[[1 2 3]
 [4 5 6]]


In [76]:
b[0]

array([1, 2, 3])

In [77]:
b[1]

array([4, 5, 6])

In [78]:
b[:,0]

array([1, 4])

In [80]:
b[0,:]

array([1, 2, 3])

## We can pass axis values in concatenate

- axis 0: row wise stacking: vstack
- axis 1: column wise stacking: hstack

In [81]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a, b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [82]:
np.hstack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# @ and matmul are exactly same
# np.dot: support scalar multiplication as well

In [85]:

list1 = [1,2,3]
list2 = [5,6]

print(list1 + list2)

[1, 2, 3, 5, 6]


In [86]:
list1.extend(list2)
list1

[1, 2, 3, 5, 6]

In [ ]:
import numpy as np
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a, b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.hstack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])