<a href="https://colab.research.google.com/github/megharajs07/DAV1/blob/main/DAV_01_Numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [ ]:
pip install numpy

In [ ]:
a = [1, 2, 3, 4, 5]
type(a)

list

In [ ]:
b = [i*i for i in a]
print(b)

[1, 4, 9, 16, 25]


In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

In [ ]:
y = x ** 2
print(y)

[ 1  4  9 16 25]


In [ ]:
l = range(1000000)
%timeit [i**2 for i in l]

330 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
arr = np.array(range(1000000))
%timeit arr**2

816 µs ± 46.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
print(x)

[1 2 3 4 5]


In [ ]:
x.ndim

1

In [ ]:
x2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x2.ndim

2

In [ ]:
x2.shape

(3, 3)

In [ ]:
x.shape

(5,)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


In [ ]:
import numpy as np
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
score = np.loadtxt('survey.txt', dtype ='int')

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 10.2MB/s]


In [ ]:
cnt = len(score)
promoters = score[score>=9]
dractors = score[score < 7]



array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,
       10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9, 10,  9, 10, 10, 10,  9,
        9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9,
        9, 10,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9,  9, 10, 10,  9, 10,
        9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10, 10,
        9, 10, 10, 10, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9, 10, 10, 10,  9,  9, 10, 10,  9,  9,  9,  9, 10,  9,  9,
        9,  9, 10, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10,  9,  9,  9,
       10,  9, 10, 10,  9,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9, 10,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9, 10, 10, 10, 10, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9, 10,
        9, 10, 10, 10, 10,  9, 10, 10,  9, 10,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9,  9,  9